name = "navsite-3ic"
compatibility_date = "2024-09-25"

[vars.production]
GITHUB_ID = "0v231ilQo0pEZyA0vb1j"
GITHUB_SECRET = "745d17163cc3fdcc3d5f90b747a09bff7084683d"  
GITHUB_OWNER = "CloudCoder825"
GITHUB_REPO = "nav-data"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsite-3ic.pages.dev/api/auth"
NEXT_PUBLIC_API_URL = "https://navsite-3ic.pages.dev"

[vars.preview]
GITHUB_ID = "0v231ilQo0pEZyA0vb1j"
GITHUB_SECRET = "745d17163cc3fdcc3d5f90b747a09bff7084683d"  
GITHUB_OWNER = "CloudCoder825"
GITHUB_REPO = "nav-data"
NEXTAUTH_URL = "https://navsite-3ic.pages.dev/api/auth"
NEXT_PUBLIC_API_URL = "https://navsite-3ic.pages.dev"
